@echo off

mkdir out 2> NUL

if "%~1"=="" (

	if exist out\vimstuff.txt (
		set /p vimstuff=<out\vimstuff.txt
		goto :found_vimstuff
	) else (
		set /p vimstuff="Folder for vim stuff (undo, backup, swap): "
	)

) else (
	set vimstuff=%1
)

(echo %vimstuff%) > out\vimstuff.txt

:found_vimstuff

mkdir "%vimstuff%" 2>NUL
mkdir "%vimstuff%\swap" 2>NUL
mkdir "%vimstuff%\backup" 2>NUL
mkdir "%vimstuff%\undo" 2>NUL

echo Set-up vimstuff to: %vimstuff%

(
	echo " Autogenerated by virmc/install.bat
	echo let s:vimstuff='%vimstuff:\=/%'
	echo.
	type vimrc
) > out\gen_vimrc

copy out\gen_vimrc "%USERPROFILE%/_vimrc" > NUL
copy gvimrc "%USERPROFILE%/_gvimrc" > NUL

