@echo off

mkdir out 2> NUL

if "%~1"=="" (

	if exist out\vimstuff.txt (
		set /p vimstuff=<out\vimstuff.txt
		goto :found_vimstuff
	) else (
		set /p vimstuff="Folder for vim stuff (undo, backup, swap): "
	)

) else (
	set vimstuff=%1
)

(echo %vimstuff%) > out\vimstuff.txt

:found_vimstuff

mkdir "%vimstuff%" 2>NUL
mkdir "%vimstuff%\swap" 2>NUL
mkdir "%vimstuff%\backup" 2>NUL
mkdir "%vimstuff%\undo" 2>NUL

echo Set-up vimstuff to: %vimstuff%

set has_vundle=0

pushd "%USERPROFILE%
    mkdir vimfiles\bundle 2>NUL
    cd vimfiles\bundle
    if exist Vundle.vim (
        set has_vundle=1
    ) else (
        git clone https://github.com/gmarik/Vundle.vim.git Vundle.vim ^
        && set has_vundle=1 && echo Set up Vundle
    )
popd
    
if %has_vundle%==1 (
    echo Vundle enabled.
) else (
    echo Skipping setting up Vundle packages, git required.
)

(
	echo " Autogenerated by `virmc/install.bat`
	echo let s:vimstuff='%vimstuff:\=/%'
	echo.
    if %has_vundle%==1 (
        echo " Copied from `virmc/vimbundle`
        type vimbundle
        echo.
    )
	echo " Copied from `virmc/vimrc`
	type vimrc
) > out\gen_vimrc

if not exist "%USERPROFILE%\_vimrc_bqq" (
	vim -u NONE "%USERPROFILE%\_vimrc" "+setlocal fo=" ^
		"+normal Oso ~/_vimrc_bqq" "+normal o"
)
copy out\gen_vimrc "%USERPROFILE%\_vimrc_bqq" > NUL

vim +PluginClean! +PluginInstall +qall

